language: python
python:
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y moreutils
install:
  - npm install -g csslint jscs
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
script:
- pre-commit install
- pre-commit run --all-files
