language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y moreutils
install: make install
script:
  - make check
  - make test
notifications:
  email:
    on_success: never